#!/bin/bash
#
# Last mod 2023-01-02, by VU3ZAN Sunil Aruldas
# Bash file for recovering and recording the band name and time for 
# activation of fixed and rotating bands in the utility environment for  ~/rtlsdr-wsprd/rtlsdr_wsprd
# NOTE: rtlsdr_wsprd is a WSPR daemon by Guenael VA2GKA on Github. RESPECT!!

# This script, located in ~/wsprd, is called by all the fixed and rotating band scripts, 
# since the coding is common for all.
# Variable 'this_band' has been passed from each calling band script, 
# referring to the current band of WSPR operation.

# recovering description of previous band
    echo $'\n'"----------------------------------------------" >> ~/wsprd/wlogs/wsprd.log 
    prevfile="$HOME/wsprd/wlogs/wsprband.txt"
    # In the above line the tilde ~ is replaced by $HOME for use in the variable
    while read -r prev_item
    do
        # writing description of previous band to wsprd.log
        echo "$prev_item" >> ~/wsprd/wlogs/wsprd.log 
    done < "$prevfile"
    
# recovering time of activation of previous band
    prevfile="$HOME/wsprd/wlogs/wsprbandtime.txt"
    while read -r prev_item
    do
        # writing time of activation of previous band to wsprd.log
        echo "$prev_item" >> ~/wsprd/wlogs/wsprd.log 
    done < "$prevfile"

 # NOTE: The running rtlsdr_wsprd session for previous band needs to be killed before a new session can be created 
 # for the current band. Since this causes it to dump all records of previous band to the wsprd.log file, the activation time 
 # and name of previous band need to be written to the file first, which has been taken care of above.
 
# recording description of current ## band and the specific script being used for it. 
# This can be checked through the ~/bin/wwband script
    curr_band="Running reception on ""$this_band"" meters"  
    echo "$curr_band" > ~/wsprd/wlogs/wsprband.txt  
    curr_script=$(basename -- "$0")
    echo "Using script : ""$curr_script" >> ~/wsprd/wlogs/wsprband.txt 
    
# recording time of current band activation for use when the next band is activated
    echo "$(date)" > ~/wsprd/wlogs/wsprbandtime.txt  

# end of file
