#!/bin/bash
#
# Last mod 2023-01-06 by VU3ZAN Sunil Aruldas
# bash file 'ww-rotate' for Guenael rtlsdr_wsprd current log in ~/wsprd/wlogs/wsprd.log 
# to rotate 6 band files by renaming them as 1 to 6 in rotation, triggered by crontab at 9.55am every day
# when the rotation feature has been activated through crontab
# 
mv ~/wsprd/6mR  ~/wsprd/0mR
# this file 0mR is a temporary placeholder file, to be renamed as 1mR at the end 
sleep 2
mv ~/wsprd/5mR  ~/wsprd/6mR
sleep 2
mv ~/wsprd/4mR  ~/wsprd/5mR
sleep 2
mv ~/wsprd/3mR  ~/wsprd/4mR
sleep 2
mv ~/wsprd/2mR  ~/wsprd/3mR
sleep 2
mv ~/wsprd/1mR  ~/wsprd/2mR
sleep 2
mv ~/wsprd/0mR  ~/wsprd/1mR
sleep 2

# the earlier file 1mR has become 2mR, earlier file 2mR has become 3mR and so on 
# Since the band selection is hard coded inside the band scripts, this means that 
# the crontab schedule will effectively cause a different sequence of bands to be activated
# thus enabling rotation of bands
# The sleep 2 seconds command is to make sure the renaming is over

# end of file
