#!/bin/bash
# 
# last mod on 2023-01-06 by VU3ZAN Sunil Aruldas
# Bash file 'wwaccess' to include $HOME/wspr/utils in the path
# to enable scripts located here to be run from anywhere
# NOTE: one executable version of this script should also be copied to $HOME
# Usage : '. wwaccess' 
# Used during development

echo
echo Old Path
echo $PATH
echo New Path
export PATH="$HOME/wsprd/utils:$PATH"
echo $PATH
echo

# end of file
