#!/bin/bash
# 
# last mod on 2023-01-06 by VU3ZAN Sunil Aruldas
# Bash file 'wwpath' to show the existing System Path
# If you want to add $Home/wsprd/utils to the System Path, use the companion script wwaccess
# Used during development
echo
echo "This is the present PATH used by the system:"
echo
echo $PATH
echo
echo "    If '$HOME/wsprd/utils' is NOT seen in the above line, then" 
echo "    the wsprd utility scripts cannot be run easily or conveniently,"
echo "    except from the $HOME/wsprd/utils directory itself."
echo
echo "      So, for convenience of operation,  please run the script 'wwaccess' "
echo "      in the $HOME directory as follows --- '. wwaccess' "
echo "      This will automatically include '$HOME/wsprd/utils' in the system PATH"
echo

# end of file
