#!/bin/bash
#
# Last mod 2023-01-06 by VU3ZAN Sunil Aruldas
# Bash file 'wwtrack' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to view it as default without giving any file name.
# NOTE : This MONITORS the current log file, displaying data as and when it is written to file 
# ALSO NOTE: This will HANG after the daily backup is carried out, 
# when the existing wsprd.log file is renamed as backups/b1.log and replaced by a new wsprd.log
# You can EXIT this script by Ctrl-C both normally and when hanging

echo 
less +F ~/wsprd/wlogs/wsprd.log
echo " * File under analysis : ~/wsprd/wlogs/wsprd.log" 
wc -l ~/wsprd/wlogs/wsprd.log

echo

# end of file
