#!/bin/bash
#
# Last mod 2022-12-22 by VU3ZAN Sunil Aruldas
# bash file 'ww-kill-rtlsdr' for Guenael rtlsdr_wsprd  
# to stop the running of the rtlsdr_wsprd process(es)

sudo killall rtlsdr_wsprd
echo "  ## WSPRD DAEMON TERMINATED  ##  (until next activation by crontab)"

# end of program
