#!/bin/bash
# 
# last mod on 2022-12-24 by VU3ZAN Sunil Aruldas
# Bash file 'wwaccess' to include $HOME/wspr/scripts in the path
# to enable scripts there to be run from anywhere
# NOTE: only one executable version of this script should be there, in $HOME
# Usage : '. wwaccess' 
echo
echo Old Path
echo $PATH
echo New Path
export PATH="$HOME/wsprd/scripts:$PATH"
echo $PATH
echo

# end of program
