#!/bin/bash
#
# Last mod 2022-12-22 by VU3ZAN Sunil Aruldas
# bash file 'wwband' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to find which wspr band is under use
echo
cat ~/wsprd/wlogs/wsprband.txt
echo

# end of program
