#!/bin/bash
#
# Last mod 2023-01-03 by VU3ZAN Sunil Aruldas
# Bash file 'wwcount' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log
# to put all Spots, counted frequency wise, in a file ~/wsprd/wlogs/wwcount.rpt 
# to view as default without giving any file name.
# Also analyze the backup logs in $HOME/wsprd/wlogs/backups/ 
# Used thus "wwquick bn" where n is 1 to 8 for each of 8 backup log files b1.log to b8.log. 
# Also analyze the wwvalidlist.log in $HOME/wsprd/wlogs/ by giving 'valid'


# Now the beginning is modified for calling by script file wwmenu
# genfile=$1
echo
echo This is Utility Script '** wwcount **' for Guenael rtlsdr_wsprd log 
echo
echo "Please enter Blank for Default (wsprd.log) or b1 to b8 for 8 days backup logs"
echo "or 'valid' for using the wwvalidlist.log"
echo "Entry ?  "
read genfile

fullfile=""
logfile="$HOME/wsprd/wlogs/wsprd.log"

if 
	[ -z $genfile ] # file name is not given, variable is empty
then
	fullfile="$logfile" # default file is current wsprd.log
else
	case $genfile in
		b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)
			genfile2="$genfile"".log"
			fullfile="$HOME/wsprd/wlogs/backups/""$genfile2";;
		valid)
			genfile2="ww""$genfile""list.log"
			fullfile="$HOME/wsprd/wlogs/""$genfile2";;
		*)
			echo
			echo "Sorry! No such file exists/permitted"
			echo "Please enter Blank for default, or file name 'b1' to 'b8' only, or 'valid'"
			echo
			exit;;
	esac

fi

echo " * File under analysis : ""$fullfile"

 echo Bash file 'wwcount' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log   > ~/wsprd/wlogs/wwcount.rpt
 echo to put all Spots, counted frequency wise, in a file ~/wsprd/wlogs/wwcount.rpt  >> ~/wsprd/wlogs/wwcount.rpt
 echo to view as default without giving any file name.  >> ~/wsprd/wlogs/wwcount.rpt
 echo Also analyze the backup logs in $HOME/wsprd/wlogs/backups/  >> ~/wsprd/wlogs/wwcount.rpt
 echo Used thus "wwcount bn" where n is 1 to 8 for each of 8 log files b1.log to b8.log. >> ~/wsprd/wlogs/wwcount.rpt
 echo Also analyze the wwvalidlist.log in $HOME/wsprd/wlogs/ >> ~/wsprd/wlogs/wwcount.rpt
 echo >> ~/wsprd/wlogs/wwcount.rpt
 echo " * File under analysis : ""$fullfile" >> ~/wsprd/wlogs/wwcount.rpt
 echo "For the FILE VIEWER, f / b / q = forward / backward / quit"  >> ~/wsprd/wlogs/wwcount.rpt
 echo >> ~/wsprd/wlogs/wwcount.rpt
echo " * Report File  : ~/wsprd/wlogs/wwcount.rpt"



 echo "Counting for 6m" >> ~/wsprd/wlogs/wwcount.rpt
 grep '50\.29' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  '50\.29' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt

 echo "Counting for 10m" >> ~/wsprd/wlogs/wwcount.rpt
 grep '28\.12' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  '28\.12' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt

 echo "Counting for 15m" >> ~/wsprd/wlogs/wwcount.rpt
 grep '21\.09' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  '21\.09' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt

 echo "Counting for 20m" >> ~/wsprd/wlogs/wwcount.rpt
 grep '14\.09' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  '14\.09' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt

 echo "Counting for 40m" >> ~/wsprd/wlogs/wwcount.rpt
 grep ' 7\.03' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  ' 7\.03' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt

 echo "Counting for 80m" >> ~/wsprd/wlogs/wwcount.rpt
 echo    for both new and old 80m wspr frequency >> ~/wsprd/wlogs/wwquick-back.log
 grep ' 3\.5' $fullfile  >> ~/wsprd/wlogs/wwcount.rpt
 grep  ' 3\.5' $fullfile  -c >> ~/wsprd/wlogs/wwcount.rpt
 # allowing for old 80m wspr frequency still in use 
# Pl Note: two decimal points are given for each frequency [except 80m]
# because otherwise the wwspot program is giving false positives by picking up values like
# 21.0 in some other column

 # cat ~/wsprd/wlogs/wwcount.rpt
 less  ~/wsprd/wlogs/wwcount.rpt 
 echo

# end of file
