#!/bin/bash
#
# Last mod 2022-12-22 by VU3ZAN Sunil Aruldas
# Bash file 'wwfreq' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to list Dial frequencies of band hopping in a file ~/wsprd/wlogs/wwfreq.rpt
# and to analyze with less as default without giving any file name.
# Also analyze the backup logs in $HOME/wsprd/wlogs/backups/ by giving b1 to b8
# for 8 days backup logs.
# Used thus "wwfreq bn" where n is 1 to 8 for each of 8 log files b1.log to b8.log. 

genfile=$1
fullfile=""
logfile="$HOME/wsprd/wlogs/wsprd.log"

if 
	[ -z $genfile ] # file name is not given, variable is empty
then
	fullfile="$logfile" # default file is current wsprd.log
else
	case $genfile in
		b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)
			genfile2="$genfile"".log"
			fullfile="$HOME/wsprd/wlogs/backups/""$genfile2";;
		*)
			echo
			echo "Sorry! No such file exists/permitted"
			echo "Please enter file name 'b1' to 'b8' only"
			echo
			exit;;
	esac

fi

echo " * File under analysis : ""$fullfile"

 echo Bash file 'wwfreq' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log > ~/wsprd/wlogs/wwfreq.rpt
 echo to list Dial frequencies of band hopping in a file ~/wsprd/wlogs/wwfreq.rpt  >> ~/wsprd/wlogs/wwfreq.rpt
 echo and to read with less as default without giving any file name.  >> ~/wsprd/wlogs/wwfreq.rpt
 echo Also read the backup logs in $HOME/wsprd/wlogs/backups/ by giving b1 to b8  >> ~/wsprd/wlogs/wwfreq.rpt
 echo for 8 days backup logs.  >> ~/wsprd/wlogs/wwfreq.rpt
 echo >> ~/wsprd/wlogs/wwfreq.rpt
 echo " * File under analysis : ""$fullfile">> ~/wsprd/wlogs/wwfreq.rpt
 echo >> ~/wsprd/wlogs/wwfreq.rpt

grep 'Dial freq.' "$fullfile" >> ~/wsprd/wlogs/wwfreq.rpt

# cat ~/wsprd/wlogs/wwfreq.rpt
less  ~/wsprd/wlogs/wwfreq.rpt
wc  -l  ~/wsprd/wlogs/wwfreq.rpt 
echo "(less 8 lines used for description heading)"
echo

# end of program
