#!/bin/bash
#
# Last mod 2023-01-03 by VU3ZAN Sunil Aruldas
# bash file 'wwhelp' for Guenael rtlsdr_wsprd utility scripts in ~/wsprd/scripts
# to list them with a short description of each, for use with wwmenu script,
# by displaying the file ~/wsprd/scripts/wsprd-script-list-for-menu.txt

cat ~/wsprd/scripts/wsprd-script-list-for-menu.txt

# end of program
