#!/bin/bash
#
# Last mod 2022-12-22 by VU3ZAN Sunil Aruldas
# bash file 'wwhelp' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to find which wspr band is under use

cat ~/wsprd/scripts/wsprd-bin-list.txt

# end of program
