#!/bin/bash
#
# last mod on 2022-12-22 by VU3ZAN Sunil Aruldas
# Bash file 'wwjump' to include $HOME/wspr/scripts in the RPi path
# in order to enable scripts there to be run from anywhere
# NOTE: only one executable version of this script should be there, in $HOME
# Usage :  '. wwjump' 
echo
cd ~/wsprd/scripts
pwd
ls
echo

# end of program
