#!/bin/bash
#
# Last mod 2023-01-03 by VU3ZAN Sunil Aruldas
# Bash file 'wwmenu' for running utility scripts for utility environment for
# Guenael rtlsdr_wsprd 
# This file is located in $HOME/wsprd/scripts and calls $HOME/wsprd/scripts/wwhelp to display the menu
# It accepts the menu serial number, which is used to call the appropriate utility script.
# Enter 00 to Exit

clear

while bash wwhelp

do
	echo
	echo please enter menu serial number : ?
	read gmenu
	clear

	if 
		[ -z $gmenu ] # file name is not given, variable is empty
	then
		echo
		echo You have not entered anything as yet, please try again
		echo Press ENTER to continue ...
		read genpause
		echo
	else
		echo "Menu Selection : $gmenu"
		case $gmenu in
			1)
				bash $HOME/wsprd/scripts/wwlive;;
			2)
				bash $HOME/wsprd/scripts/wwping;;
			3)
				bash $HOME/wsprd/scripts/wwband;;
			4)
				bash $HOME/wsprd/scripts/wwspot;;
			5)
				bash $HOME/wsprd/scripts/wwcount;;
			6)
				bash $HOME/wsprd/scripts/wwquick;;
			7)
				bash $HOME/wsprd/scripts/wwlog;;
			8)
				bash $HOME/wsprd/scripts/wwtrack;;
			9)
				bash $HOME/wsprd/scripts/wwfreq;;
			10)
				bash $HOME/wsprd/scripts/wwtime;;
			11)
				bash $HOME/wsprd/scripts/wwvu;;
			# 12)
				# bash $HOME/wsprd/scripts/ww-timesync;;
			# disabled because ntp is having problems in raspbian bullseye
			# and anyway systemd-timesyncd is taking over it seems
			00)
				echo
				echo
				echo You have chosen to exit this utility menu for wsprd ...
				echo Exiting ...
				exit;;
			# if 'bash wwmenu' was used to run this, it will return to the command line,
			# otherwise it will exit the terminal completely
			*)
				echo
				echo You have entered 
				echo "$gmenu"
				echo Sorry! No such file exists/permitted
				# echo Please enter Menu numbers 1 to 12, or '00' only
				echo Please enter Menu numbers 1 to 11, or '00' only
				echo;;
		esac
	
		echo Press ENTER to continue ...
		read genpause

	fi


done


