#!/bin/bash
#
# Last mod 2023-01-03 by VU3ZAN Sunil Aruldas
# Bash file 'wwspot' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to put all Spots in a file ~/wsprd/wlogs/wwspot.rpt
# to view as default without giving any file name.
# Also analyze the backup logs in $HOME/wsprd/wlogs/backups/ 
# Used thus : 'wwspot bn'  --- where n is 1 to 8 for each of 8 backup log files b1.log to b8.log.

# Now the beginning is modified for calling by script file wwmenu
# genfile=$1
echo
echo This is Utility Script '** wwspot **' for Guenael rtlsdr_wsprd log 
echo
echo "Please enter Blank for Default (wsprd.log) or b1 to b8 for 8 days backup logs"
echo "Entry ?  "
read genfile

fullfile=""
logfile="$HOME/wsprd/wlogs/wsprd.log"

if 
	[ -z $genfile ] # file name is not given, variable is empty
then
	fullfile="$logfile" # default file is current wsprd.log
else
	case $genfile in
		b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)
			genfile2="$genfile"".log"
			fullfile="$HOME/wsprd/wlogs/backups/""$genfile2";;
		*)
			echo
			echo "Sorry! No such file exists/permitted"
			echo "Please enter Blank for default, or file name 'b1' to 'b8' only"
			echo
			exit;;
	esac

fi

echo " * File under analysis : ""$fullfile"

 echo Bash file 'wwspot' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log   > ~/wsprd/wlogs/wwspot.rpt
 echo to put all Spots in a file ~/wsprd/wlogs/wwspot.rpt  >> ~/wsprd/wlogs/wwspot.rpt
 echo to view as default, without giving any file name.  >> ~/wsprd/wlogs/wwspot.rpt
 echo Also analyze the backup logs in $HOME/wsprd/wlogs/backups/   >> ~/wsprd/wlogs/wwspot.rpt
 echo Used thus :  'wwquick bn' --- where n is 1 to 8 for each of 8 backup log files b1.log to b8.log.  >> ~/wsprd/wlogs/wwspot.rpt
 echo >> ~/wsprd/wlogs/wwspot.rpt
 echo " * File under analysis : ""$fullfile" >> ~/wsprd/wlogs/wwspot.rpt
 echo "For the FILE VIEWER, f / b / q = forward / backward / quit"  >> ~/wsprd/wlogs/wwspot.rpt
 echo "                    UTC" >> ~/wsprd/wlogs/wwspot.rpt
 echo  >> ~/wsprd/wlogs/wwspot.rpt
echo " * Report File  : ~/wsprd/wlogs/wwspot.rpt"


grep 'Spot :' "$fullfile" >> ~/wsprd/wlogs/wwspot.rpt

less ~/wsprd/wlogs/wwspot.rpt
echo
wc  -l ~/wsprd/wlogs/wwspot.rpt 
echo "(less 9 lines used for description heading)"
echo

# end of file
