#!/bin/bash
# bash file 'wstc' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to list times of band hopping in a file ~/wsprd/wlogs/wstc.log

echo
grep 'IST' ~/wsprd/wlogs/wsprd.log > ~/wsprd/wlogs/wstc.log
cat ~/wsprd/wlogs/wstc.log
wc  ~/wsprd/wlogs/wstc.log 
# -NO DESC- echo "(less 8 lines used for description heading)"
echo
