#!/bin/bash
#
# Last mod 24-12-2022 by VU3ZAN Sunil Aruldas
# Bash file 'wwtrack' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log 
# to read with less as default without giving any file name.
# NOTE : This MONITORS the log file, displaying data as it is written to file 
echo 
less +F ~/wsprd/wlogs/wsprd.log
echo " * File under analysis : ~/wsprd/wlogs/wsprd.log" 
wc -l ~/wsprd/wlogs/wsprd.log
# -NO DESC- echo "(less 8 lines used for description heading)"
echo

# end of program
