#!/bin/bash
#
# Last mod 2023-01-06 by VU3ZAN Sunil Aruldas
# bash file 'wwvu' for Guenael rtlsdr_wsprd log in ~/wsprd/wlogs/wsprd.log
# in ~/wsprd/wlogs/backups/, plus  ~/wsprd/wlogs/wwvalidlist.log
# to remove Spots with 'A000AA' & '<...>' while putting all "VU" [Indian] Spots in a file ~/wsprd/wlogs/wwvu.rpt
# Fresh analysis every time
# to view as default without giving any file name.
# Also analyze the backup logs in $HOME/wsprd/wlogs/backups/ 
# Used thus : 'wwspot bn'  --- where n is 1 to 8 for each of 8 backup log files b1.log to b8.log

# Also analyze the wwvalidlist.log in $HOME/wsprd/wlogs/ by giving 'valid'

# Now the beginning is modified for calling by script file wwmenu
# genfile=$1
echo
echo This is Utility Script '** wwvu **' for Guenael rtlsdr_wsprd log 
echo
echo "Please enter Blank for Default (wsprd.log) or b1 to b8 for 8 days backup logs"
echo "or 'valid' for using the wwvalidlist.log"
echo "Entry ?  "
read genfile

fullfile=""
logfile="$HOME/wsprd/wlogs/wsprd.log"

if 
	[ -z $genfile ] # file name is not given, variable is empty
then
	fullfile="$logfile" # default file is current wsprd.log
else
	case $genfile in
		b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)
			genfile2="$genfile"".log"
			fullfile="$HOME/wsprd/wlogs/backups/""$genfile2";;
		valid)
			genfile2="ww""$genfile""list.log"
			fullfile="$HOME/wsprd/wlogs/""$genfile2";;
		*)
			echo
			echo "Sorry! No such file exists/permitted"
			echo "Please enter Blank for default, or file name 'b1' to 'b8' only, or 'valid'"
			echo
			exit;;
	esac

fi

echo " * File under analysis : ""$fullfile"


 echo Bash file 'wwvu' for Guenael rtlsdr_wsprd current log in ~/wsprd/wlogs/, and 8 backup logs > ~/wsprd/wlogs/wwvu.rpt
 echo in ~/wsprd/wlogs/backups/, plus  ~/wsprd/wlogs/wwvalidlist.log >> ~/wsprd/wlogs/wwvu.rpt
 echo "to remove Spots with 'A000AA' & '<...>' while putting all "VU" [Indian]"  >> ~/wsprd/wlogs/wwvu.rpt
 echo Spots in a file ~/wsprd/wlogs/wwvu.rpt >> ~/wsprd/wlogs/wwvu.rpt
 echo Fresh analysis every time >> ~/wsprd/wlogs/wwvu.rpt
 echo to view as default without giving any file name. >> ~/wsprd/wlogs/wwvu.rpt
 echo Also analyze the backup logs in $HOME/wsprd/wlogs/backups/  >> ~/wsprd/wlogs/wwvu.rpt
 echo Used thus : 'wwspot bn'  --- where n is 1 to 8 for each of 8 backup log files b1.log to b8.log >> ~/wsprd/wlogs/wwvu.rpt
 echo Also analyze the wwvalidlist.log in $HOME/wsprd/wlogs/ >> ~/wsprd/wlogs/wwvu.rpt

 echo >> ~/wsprd/wlogs/wwvu.rpt
 echo " * File under analysis : ""$fullfile" >> ~/wsprd/wlogs/wwvu.rpt
 echo "For the FILE VIEWER, f / b / q = forward / backward / quit"  >> ~/wsprd/wlogs/wwvu.rpt
 echo >> ~/wsprd/wlogs/wwvu.rpt
 echo " * Report File  : ~/wsprd/wlogs/wwvu.rpt"

  grep 'Spot : ' "$fullfile" | grep 'VU2\|VU3' | grep -v 'A000AA\|<...>' >> ~/wsprd/wlogs/wwvu.rpt
  grep 'Spot : ' "$fullfile" | grep 'VU2\|VU3' | grep -v 'A000AA\|<...>' -c >> ~/wsprd/wlogs/wwvu.rpt

 less ~/wsprd/wlogs/wwvu.rpt
  wc  -l ~/wsprd/wlogs/wwvu.rpt 
  echo "(less 12 lines used for description heading)"
  echo

  
  # end of file

